sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - zf-mkdoc-theme

env:
  global:
    - SITE_URL: https://zendframework.github.io/zend-component-installer
    - GH_USER_NAME: "Matthew Weier O'Phinney"
    - GH_USER_EMAIL: matthew@weierophinney.net
    - GH_REF: github.com/zendframework/zend-component-installer.git
    - secure: "moDyn4E7j7f2KhiRJK8z5Ps3tJ9EB37MBLQq78NJqmPBRttiCG5PQ2ru62MCQhXKPncjDVd6d9TwA3DRryF49mLqLOYHwYuFM6sgdtRbHi9d5X8jxorsABqFI3d9Wu/A8+vwbmjpw5MPKH96k7n5IaDSCsmsd8jX95gdztybOx+BZ5PY1paJyfwydTo320s9ev0g6yTHlG9LYHhtmPyrog/4Vxsm2yUcEOFLQjY2EwLNTlqQJ3c5LrOaELsZZHwpPTItjX5iQgOs/A3XYsbZHjzFcY4m9wnHryhhTAD5QKyu1kf+XewZfNn+7ROCKGXOJoYb9+mOEL7p3vrQQK9Y16GN2IXn7mAHBJpAefl3aaJFyhf17eyXwDDSCFIBvSZsLZfm/lyJQXhwCuT49sdDDGz3uR5IZ8Zl4n0eiiR7s9QvxNV288zJs7BiWAyU7bRoXe3zkraKbmiqz5LW6ko1Qm3oUzZsRp7oSjzuLg+jO8CccGIY/jhOSaj24tw9aIw8iYNV9/QzR/ncHi/i3v6fOYX+tjoF8Fao9RrBMRkKCywTrm9F9eOO6rDUSHj43eXvQ7awQXoK5DZTwUGwCFkj+2f1FfQw23m8e6dTS4eLdmb2PWQuD28Q/x5+HeAo9TXSJTBsXEGeSTbW/35lMbbtq36eo+3OJnVcQFHNeg3+34U="


matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
      - EXECUTE_CS_CHECK=true
    - php: 5.6
        env:
          - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
          - PATH="$HOME/.local/bin:$PATH"
    - php: 7
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update

install:
  - travis_retry composer install --no-interaction
  - composer info -i

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer test-coverage ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then composer test ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer cs ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then wget -O theme-installer.sh "https://raw.githubusercontent.com/zendframework/zf-mkdoc-theme/master/theme-installer.sh" ; chmod 755 theme-installer.sh ; ./theme-installer.sh ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./zf-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi

after_script:
- if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer coveralls ; fi

notifications:
  email: true
